### ISSUE TITLE
Provide a Gradle Dependency

### ISSUE THREAD

**Issue by droidchef** [curioustechizen/yadi#3]
Host the compiled library as a repository and allow users to add them into their gradle based projects like so 

`compile 'in.kiranrao.yadi:yadi:1.0-SNAPSHOT'`

**Comment by curioustechizen** [comment]
This is on my radar too. Just felt too lazy to go through all the Maven Central publishing hoops (it'll definitely take me 5x the time it took me to write the lib in the first place :stuck_out_tongue: ). Till then I'll probably make the repo [jitpack-compatible](https://jitpack.io).

**Comment by droidchef** [comment]
Sounds Good :smile:
